@startuml GameLogic
state "GameLogic State" as DodgeTheCreeps_GameLogic_State {
  state "Lost" as DodgeTheCreeps_GameLogic_State_Lost
  state "MenuBackdrop" as DodgeTheCreeps_GameLogic_State_MenuBackdrop
  state "Paused" as DodgeTheCreeps_GameLogic_State_Paused {
    state "Saving" as DodgeTheCreeps_GameLogic_State_Saving
  }
  state "Playing" as DodgeTheCreeps_GameLogic_State_Playing
  state "Quit" as DodgeTheCreeps_GameLogic_State_Quit
  state "RestartingGame" as DodgeTheCreeps_GameLogic_State_RestartingGame
  state "Resuming" as DodgeTheCreeps_GameLogic_State_Resuming
}

DodgeTheCreeps_GameLogic_State_Lost --> DodgeTheCreeps_GameLogic_State_Quit : GoToMainMenu
DodgeTheCreeps_GameLogic_State_Lost --> DodgeTheCreeps_GameLogic_State_RestartingGame : Start
DodgeTheCreeps_GameLogic_State_MenuBackdrop --> DodgeTheCreeps_GameLogic_State_MenuBackdrop : Initialize
DodgeTheCreeps_GameLogic_State_MenuBackdrop --> DodgeTheCreeps_GameLogic_State_Playing : Start
DodgeTheCreeps_GameLogic_State_Paused --> DodgeTheCreeps_GameLogic_State_Quit : GoToMainMenu
DodgeTheCreeps_GameLogic_State_Paused --> DodgeTheCreeps_GameLogic_State_Resuming : PauseButtonPressed
DodgeTheCreeps_GameLogic_State_Paused --> DodgeTheCreeps_GameLogic_State_Saving : SaveRequested
DodgeTheCreeps_GameLogic_State_Playing --> DodgeTheCreeps_GameLogic_State_Lost : EndGame
DodgeTheCreeps_GameLogic_State_Playing --> DodgeTheCreeps_GameLogic_State_Paused : PauseButtonPressed
DodgeTheCreeps_GameLogic_State_Playing --> DodgeTheCreeps_GameLogic_State_Playing : MobTimerTimeout
DodgeTheCreeps_GameLogic_State_Playing --> DodgeTheCreeps_GameLogic_State_Playing : ScoreTimerTimeout
DodgeTheCreeps_GameLogic_State_Playing --> DodgeTheCreeps_GameLogic_State_Playing : StartTimerTimeout
DodgeTheCreeps_GameLogic_State_Playing --> DodgeTheCreeps_GameLogic_State_Quit : EndGame
DodgeTheCreeps_GameLogic_State_Resuming --> DodgeTheCreeps_GameLogic_State_Playing : PauseMenuTransitioned
DodgeTheCreeps_GameLogic_State_Saving --> DodgeTheCreeps_GameLogic_State_Paused : SaveCompleted
DodgeTheCreeps_GameLogic_State_Saving --> DodgeTheCreeps_GameLogic_State_Saving : PauseButtonPressed

DodgeTheCreeps_GameLogic_State_Lost : OnEnter → ShowLostScreen
DodgeTheCreeps_GameLogic_State_Paused : OnEnter → ShowPauseMenu
DodgeTheCreeps_GameLogic_State_Paused : OnExit → ExitPauseMenu
DodgeTheCreeps_GameLogic_State_Playing : OnEnter → StartGame
DodgeTheCreeps_GameLogic_State_Playing : OnMobTimerTimeout → SpawnMob
DodgeTheCreeps_GameLogic_State_Resuming : OnExit → HidePauseMenu
DodgeTheCreeps_GameLogic_State_Saving : OnEnter → ShowPauseSaveOverlay, StartSaving
DodgeTheCreeps_GameLogic_State_Saving : OnExit → HidePauseSaveOverlay

[*] --> DodgeTheCreeps_GameLogic_State_MenuBackdrop
@enduml